local function db(name, var, suffix)
  local url = os.getenv(var)
  if not url then return nil end
  return { name = name, url = url .. (suffix or "") }
end

local candidates = {
  db("Ekonomi", "BIG_EKONOMI_EXECUTION_PROD"),
  db("VARD", "BIG_VARD_EXECUTION_PROD"),
  db("FRAPP", "BIG_FRAPP_EXECUTION_PROD"),
  db("STATISTIK", "BIG_STATISTIK_EXECUTION_PROD"),
  db("FRAPP_SOURCE", "FRAPP", "?TrustServerCertificate=yes"),
  db("BIRTH_CID", "BIRTH_CID_DADBOD"),
  db("HR", "BIG_HR_EXECUTION_PROD"),
}

-- table has nil holes, so walk by index instead of trusting pairs() order
local dbs = {}
for i = 1, #candidates + 10 do
  if candidates[i] then table.insert(dbs, candidates[i]) end
end
vim.g.dbs = dbs

local pg_ddl = [[
\t on
\a
with rel as (
  select c.oid, c.relkind, n.nspname, c.relname
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = '{schema}' and c.relname = '{table}'
),
cols as (
  select
    a.attnum as ord,
    format('    %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
      || case
           when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
           when a.attidentity = 'a' then ' generated always as identity'
           when a.attidentity = 'd' then ' generated by default as identity'
           when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
           else ''
         end
      || case when a.attnotnull then ' not null' else '' end as line
  from pg_attribute a
  join rel on rel.oid = a.attrelid
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  where a.attnum > 0 and not a.attisdropped
  union all
  select
    10000 + row_number() over (order by con.contype = 'p' desc, con.conname),
    format('    constraint %I %s', con.conname, pg_get_constraintdef(con.oid))
  from pg_constraint con
  join rel on rel.oid = con.conrelid
  where con.contype <> 'n' -- pg18 stores not null as constraints, already handled above
)
select format(E'create %s %I.%I as\n%s',
         case r.relkind when 'v' then 'view' else 'materialized view' end,
         r.nspname, r.relname, pg_get_viewdef(r.oid, true))
from rel r
where r.relkind in ('v', 'm')
union all
select format(E'create table %I.%I (\n%s\n)%s;',
         r.nspname, r.relname,
         (select string_agg(line, E',\n' order by ord) from cols),
         coalesce(' partition by ' || pg_get_partkeydef(r.oid), ''))
from rel r
where r.relkind in ('r', 'p')
union all
select pg_get_indexdef(i.indexrelid) || ';'
from pg_index i
join rel r on r.oid = i.indrelid
where not exists (
  select 1 from pg_constraint con
  where con.conindid = i.indexrelid
    and con.conrelid = r.oid
    and con.contype in ('p', 'u', 'x')
);
]]

vim.g.db_ui_table_helpers = {
  postgresql = { DDL = pg_ddl },
  sqlserver = {
    DDL = "exec sp_helptext '{schema}.{table}'",
    Structure = "exec sp_help '{schema}.{table}'",
  },
}
